export default constants={
    IDCHANGE:'IDCHANGE',
    PASSWORDCHANGE:'PASSWORDCHANGE',
    LOGINCALL:'LOGINCALL',
    LOGINSUCESSFULL:'LOGINSUCESSFULL',
    LOGINFAILS:'LOGINFAILS',
    CREATEEMPLOYEE:'CREATEEMPLOYEE'
}