const ActionTypes = {
    ALLUSERS:'ALLUSERS',
    CURRENTUSER:'CURRENTUSER',
    REEDITISL:'REEDITISL',
    ISLAMABAD:'ISLAMABAD',
    ISLAMABADVAL:'ISLAMABADVAL',
    KARACHI:'KARACHI',
    KARACHIVAL:'KARACHIVAL',
    LONDON:'LONDON',
    LONDONVAL:'LONDONVAL',
}

export default ActionTypes;
