
//import com.healthmarketscience.jackcess.Column;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shoaib
 */
public class Info extends javax.swing.JFrame {

    /**
     * Creates new form Info
     */
    Statement pst;
    public Info() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Information");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "First_name", "Last_name", "Telephone", "Salary"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   
    /**
     *
     * @param table_name
     * @param args the command line arguments
     * @throws java.sql.SQLException
     */
   public void PopulateJtable(String table_name) throws SQLException {
    JTable table= jTable2; 
       String Query = "SELECT ID,FIRST_NAME,LAST_NAME,TELEPHONE,CNIC from " + table_name;
    DefaultTableModel dtm = (DefaultTableModel) table.getModel();
    dtm.setRowCount(0);
    //dtm.setColumnCount(0);
    try {
        
        pst = Connect.conn.createStatement();
        pst.execute(Query);
        ResultSet rs = pst.getResultSet();
        int columns = table.getColumnCount();
        Vector vector = new Vector();
        while (rs.next()) {
            Vector row = new Vector();
          /*  for (int i = 0; i < columns; i++) {
        TableColumn c = new TableColumn(i);
        
        table.getColumnModel().addColumn(c);
    }*/

            for (int i = 1; i <= columns; i++) {
                row.addElement(rs.getObject(i));
                
            }
            dtm.addRow(row);
    }  
    } 
     catch (SQLException e) {
        JOptionPane.showMessageDialog(null,  "ERROR !! ");
    }
        
    }

    
    
    
    /*public void getEmployees() {
    try {
        String Query = "select * from Employee";
        PreparedStatement pst=pst = Connection.conn.prepareStatement(Query);
        ResultSet rs = pst.executeQuery(Query);
        
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));


 
     } catch(Exception e) {
         e.printStackTrace();
     }
}*/


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Info().setVisible(true);
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}


